version: '3'

tasks:
  tf-up:
    summary: |
      Bootstraps tf resources in GCP on saved plan
    cmds:
      - terraform validate
      - terraform plan -out=plan.txt
      - terraform apply -auto-approve

  tf-destroy:
    summary: |
      Tear down tf resources in GCP
    cmds:
      - terraform destroy -auto-approve

  kind-up:
    summary: |
      Bootstraps kind cluster
    cmds:
      - kind create cluster

  kind-down:
    summary: |
      Destroys kind cluster
    cmds:
      - kind delete cluster

  capi-up:
    summary: |
      Bootstraps capi providers for talos linux and vcluster in management cluster
    cmds:
      - clusterctl init --bootstrap talos --control-plane talos --infrastructure vcluster

  helm-up:
    summary: |
      Bootstraps base helm applications for management cluster
      - ArgoCD
      - Sveltos
      - Kyverno
      - etc
    cmds:
      - helmfile apply


  mgmt-up:
    deps: [kind-up]
    dir: '{{.USER_WORKING_DIR}}/infrastructure/'
    summary: |
      Verifies that cluster specification exists and initial applications to bootstrap
      Spins up kind cluster from it
    preconditions:
      - file cluster.yaml
      - file helmfile.yaml
      - kind --version
      - helmfile init
      - clusterctl version
    cmds:
      - task: capi-up
      - task: helm-up
      - kubectl create namespace vcluster
      - kubectl apply -f cluster.yaml

  mgmt-down:
    dir: '{{.USER_WORKING_DIR}}/infrastructure/'
    summary: |
      Destroys kind cluster deleting resources in orders
    cmds:
      - kubectl delete -f cluster.yaml
      - kubectl delete namespace vcluster
      - task: kind-downs