version: '3'

tasks:
  tf-up:
    summary: |
      Bootstraps tf resources in GCP on saved plan
    cmds:
      - terraform validate
      - terraform plan -out=resources
      - terraform apply -auto-approve "resources"

  tf-destroy:
    summary: |
      Tear down tf resources in GCP
    cmds:
      - terraform destroy -auto-approve

  kind-up:
    summary: |
      Bootstraps kind cluster
    cmds:
      - kind create cluster

  kind-down:
    summary: |
      Destroys kind cluster
    cmds:
      - kind delete cluster

  capi-up:
    summary: |
      Bootstraps capi providers for talos linux and vcluster in management cluster
    dotenv: [".env"]
    preconditions:
      - file credentials.json
    cmds:
      - export {{.GCP_B64ENCODED_CREDENTIALS}}
      - clusterctl init --bootstrap talos --control-plane talos --infrastructure gcp
    vars:
      GCP_B64ENCODED_CREDENTIALS:
        sh: cat credentials.json | base64 | tr -d '\n'

  helm-up:
    summary: |
      Bootstraps base helm applications for management cluster
      - ArgoCD
      - Sveltos
      - Kyverno
      - etc
    cmds:
      - helmfile apply

  cluster-class-up:
    summary: |
      Bootstraps base CAPI cluster classes based cluster size for Talos in GCP
    cmds:
      - kubectl apply -f cluster-classes/gpc*.yaml

  mgmt-up:
    deps: [kind-up]
    dir: '{{.USER_WORKING_DIR}}/infrastructure/'
    summary: |
      Verifies that cluster specification exists and initial applications to bootstrap
      Spins up kind cluster from it
    preconditions:
      - file cluster.yaml
      - file helmfile.yaml
      - kind --version
      - helmfile init
      - clusterctl version
    cmds:
      - task: capi-up
      - task: helm-up
      - kubectl create namespace gcp-cluster
      - task: cluster-class-up
      - kubectl apply -f cluster.yaml

  mgmt-down:
    dir: '{{.USER_WORKING_DIR}}/infrastructure/'
    summary: |
      Destroys kind cluster deleting resources in orders
    cmds:
      - kubectl delete -f cluster.yaml
      - kubectl delete namespace gcp-cluster
      - task: kind-down